project:
  type: website

website:
  title: "ISSS626-Kieren Chua"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Hands On Exercises
        menu:
          - text: Exercise 1
            href: HandsonEx/HandsonEx01/HandsonEx01.qmd
          - text: Exercise 2, Part 1
            href: HandsonEx/HandsonEx02/HandsonEx02.qmd
          - text: Exercise 2, Part 2
            href: HandsonEx/HandsonEx02/HandsonEx02_2.qmd
          - text: Exercise 3
            href: HandsonEx/HandsonEx03/HandsOnEx03.qmd
          - text: Exercise 4
            href: HandsonEx/HandsonEx04/HandsonEx04.qmd
          - text: Exercise 5
            href: HandsonEx/HandsonEx05/HandsonEx05.qmd
          - text: Exercise 6
            href: HandsonEx/HandsonEx06/HandsonEx06.qmd
      - text: In Class Exercise
        menu:
          - text: In Class Exercise 1
            href: InClassEx/InClassEx01/InClassEx01.qmd
          - text: In Class Exercise 3
            href: InClassEx/InClassEx03/InClassEx03.qmd
          - text: In Class Exercise 4
            href: InClassEx/InClassEx04/InClassEx04.qmd
          - text: In Class Exercise 5
            href: InClassEx/InClassEx05/InClassEx05.qmd
      - text: Take Home Exercise
        menu:
          - text: Take Home Exercise 1
            href: TakeHomeEx\TakeHomeEx01\TakeHomeEx01.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

