project:
  type: website

website:
  title: "ISSS626-Kieren Chua"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Hands On Exercises
        menu:
          - text: Exercise 1
            href: HandsonEx/HandsonEx01/HandsonEx01.qmd
          - text: Exercise 2
            href: HandsonEx/HandsonEx02/HandsonEx02.qmd
      - text: In Class Exercise
        menu:
          - text: In Class Exercise 1
            href: InClassEx/InClassEx01/InClassEx01.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

