project:
  type: website

website:
  title: "ISSS626-Kieren Chua"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Hands On Exercises
        menu:
          - text: Exercise 1
            href: HandsonEx/HandsonEx01/HandsonEx01.qmd
          - text: Exercise 2, Part 1
            href: HandsonEx/HandsonEx02/HandsonEx02.qmd
          - text: Exercise 2, Part 2
            href: HandsonEx/HandsonEx02/HandsonEx02_2.qmd
          - text: Exercise 3
            href: HandsonEx/HandsonEx03/HandsOnEx03.qmd
          - text: Exercise 4
            href: HandsonEx/HandsonEx04/HandsonEx04.qmd
          - text: Exercise 5
            href: HandsonEx/HandsonEx05/HandsonEx05.qmd
          - text: Exercise 6
            href: HandsonEx/HandsonEx06/HandsonEx06.qmd
          - text: Exercise 7
            href: HandsonEx/HandsonEx07/HandsonEx07.qmd
          - text: Exercise 8
            href: HandsonEx/HandsonEx08/HandsonEx08.qmd
          - text: Exercise 9
            href: HandsonEx/HandsonEx09/HandsonEx09.qmd
          - text: Exercise 10a
            href: HandsonEx/HandsonEx10/HandsonEx10a.qmd
          - text: Exercise 10b
            href: HandsonEx/HandsonEx10/HandsonEx10b.qmd
      - text: In Class Exercise
        menu:
          - text: In Class Exercise 1
            href: InClassEx/InClassEx01/InClassEx01.qmd
          - text: In Class Exercise 3
            href: InClassEx/InClassEx03/InClassEx03.qmd
          - text: In Class Exercise 4
            href: InClassEx/InClassEx04/InClassEx04.qmd
          - text: In Class Exercise 5
            href: InClassEx/InClassEx05/InClassEx05.qmd
          - text: In Class Exercise 6
            href: InClassEx/InClassEx06/InClassEx06.qmd
          - text: In Class Exercise 7
            href: InClassEx/InClassEx07/InClassEx07.qmd
          - text: In Class Exercise 8
            href: InClassEx/InClassEx08/InClassEx08.qmd
          - text: In Class Exercise 9
            href: InClassEx/InClassEx09/InClassEx09.qmd
          - text: In Class Exercise 10
            href: InClassEx/InClassEx10/InClassEx10.qmd
      - text: Take Home Exercise
        menu:
          - text: Take Home Exercise 1
            href: TakeHomeEx\TakeHomeEx01\TakeHomeEx01.qmd
          - text: Take Home Exercise 2
            href: TakeHomeEx\TakeHomeEx02\TakeHomeEx02.qmd
          - text: Take Home Exercise 3
            href: TakeHomeEx\TakeHomeEx03\TakeHomeEx03.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

