---
title: "Hands on Exercise 1"
author: "Kieren Chua"
date: "August 25 2024"
date-modified: "last-modified"
execute: 
    eval: true # evaulate the code first
    echo: true # See the code output
    message: false # don't see the warnings
    freeze: true # Prevent re-render
---

# Network Constrained Spatial Point Patterns Analysis

## Part 1 : Data

```{r}
pacman::p_load(sf, spNetwork, tmap, tidyverse)
```

Read the data
```{r}
network <- st_read(dsn="data", 
                   layer="Punggol_St")
childcare <- st_read(dsn="data",
                     layer="Punggol_CC")
```

## Part 2 : Visualize the Data

See the columns first
::: {.tabset}

```{r}
#| echo: true
childcare
```
```{r}
#| echo: true
network
```
:::

Plot out the data
```{r}
plot(st_geometry(network))
plot(childcare,add=T,col='red',pch = 19)
```

```{r}
tmap_mode('view')
tm_shape(childcare) + 
  tm_dots() + 
  tm_shape(network) +
  tm_lines()
tmap_mode('plot')
```


```{r}

```


## Network KDE (NKDE) Analysis

```{r}
lixels <- lixelize_lines(network, 
                         700, 
                         mindist = 375)
```

```{r}
samples <- lines_center(lixels)
```

```{r}
childcare <- st_zm(childcare)
```

```{r}
densities <- nkde(network, 
                  events = childcare,
                  w = rep(1, nrow(childcare)),
                  samples = samples,
                  kernel_name = "quartic",
                  bw = 300, 
                  div= "bw", 
                  method = "simple", 
                  digits = 1, 
                  tol = 1,
                  grid_shape = c(1,1), 
                  max_depth = 8,
                  agg = 5, 
                  sparse = TRUE,
                  verbose = FALSE)
```

Visualize the data 
```{r}
samples$density <- densities
lixels$density <- densities
```

```{r}
samples$density <- samples$density*1000
lixels$density <- lixels$density*1000
```

```{r}
tmap_mode('view')
tm_shape(lixels)+
  tm_lines(col="density")+
tm_shape(childcare)+
  tm_dots()
tmap_mode('plot')
```

## Part 3 : Network Constrained G- and K-Function Analysis

```{r}
kfun_childcare <- kfunctions(network, 
                             childcare,
                             start = 0, 
                             end = 1000, 
                             step = 50, 
                             width = 50, 
                             nsim = 50, 
                             resolution = 50,
                             verbose = FALSE, 
                             conf_int = 0.05)
```

```{r}
kfun_childcare$plotk
```
